export const products = [
  {
    name: "classic oxford button-down shirt",
    description:
      "this classic oxford shirt is tailored for a polished yet casual look. crafted from high-quality cotton, it features a button-down collar and a comfortable, slightly relaxed fit. perfect for both formal and casual occasions, it comes with long sleeves, a button placket, and a yoke at the back. the shirt is finished with a gently rounded hem and adjustable button cuffs.",
    price: 39.99,
    discountPrice: 34.99,
    countInStock: 20,
    sku: "ox-sh-001",
    category: "top wear",
    brand: "urban threads",
    sizes: ["s", "m", "l", "xl", "xxl"],
    colors: ["red", "blue", "yellow"],
    collections: "business casual",
    material: "cotton",
    gender: "men",
    images: [
      {
        url: "https://picsum.photos/500/500?random=39",
        altText: "classic oxford button-down shirt front view",
      },
      {
        url: "https://picsum.photos/500/500?random=40",
        altText: "classic oxford button-down shirt back view",
      },
    ],
    rating: 4.5,
    numReviews: 12,
  },
  {
    name: "slim-fit stretch shirt",
    description:
      "a versatile slim-fit shirt perfect for business or evening events. designed with a fitted silhouette, the added stretch provides maximum comfort throughout the day. features a crisp turn-down collar, button placket, and adjustable cuffs.",
    price: 29.99,
    discountPrice: 24.99,
    countInStock: 35,
    sku: "slim-sh-002",
    category: "top wear",
    brand: "modern fit",
    sizes: ["s", "m", "l", "xl"],
    colors: ["black", "navy blue", "burgundy"],
    collections: "formal wear",
    material: "cotton blend",
    gender: "men",
    images: [
      {
        url: "https://picsum.photos/500/500?random=41",
        altText: "slim-fit stretch shirt front view",
      },
      {
        url: "https://picsum.photos/500/500?random=42",
        altText: "slim-fit stretch shirt back view",
      },
    ],
    rating: 4.8,
    numReviews: 15,
  },
  {
    name: "casual denim shirt",
    description:
      "this casual denim shirt is made from lightweight cotton denim. it features a regular fit, snap buttons, and a straight hem. with western-inspired details, this shirt is perfect for layering or wearing solo.",
    price: 49.99,
    discountPrice: 44.99,
    countInStock: 15,
    sku: "cas-den-003",
    category: "top wear",
    brand: "street style",
    sizes: ["s", "m", "l", "xl", "xxl"],
    colors: ["light blue", "dark wash"],
    collections: "casual wear",
    material: "denim",
    gender: "men",
    images: [
      {
        url: "https://picsum.photos/500/500?random=43",
        altText: "casual denim shirt front view",
      },
      {
        url: "https://picsum.photos/500/500?random=44",
        altText: "casual denim shirt back view",
      },
    ],
    rating: 4.6,
    numReviews: 8,
  },
  {
    name: "printed resort shirt",
    description:
      "designed for summer, this printed resort shirt is perfect for vacation or weekend getaways. it features a relaxed fit, short sleeves, and a camp collar. the all-over tropical print adds a playful vibe.",
    price: 29.99,
    discountPrice: 22.99,
    countInStock: 25,
    sku: "prnt-res-004",
    category: "top wear",
    brand: "beach breeze",
    sizes: ["s", "m", "l", "xl"],
    colors: ["tropical print", "navy palms"],
    collections: "vacation wear",
    material: "viscose",
    gender: "men",
    images: [
      {
        url: "https://picsum.photos/500/500?random=45",
        altText: "printed resort shirt front view",
      },
      {
        url: "https://picsum.photos/500/500?random=1",
        altText: "printed resort shirt back view",
      },
    ],
    rating: 4.4,
    numReviews: 10,
  },
  {
    name: "slim-fit easy-iron shirt",
    description:
      "a slim-fit, easy-iron shirt in woven cotton fabric with a fitted silhouette. features a turn-down collar, classic button placket, and a yoke at the back. long sleeves and adjustable button cuffs with a rounded hem.",
    price: 34.99,
    discountPrice: 29.99,
    countInStock: 30,
    sku: "slim-eir-005",
    category: "top wear",
    brand: "urban chic",
    sizes: ["s", "m", "l", "xl"],
    colors: ["white", "gray"],
    collections: "business wear",
    material: "cotton",
    gender: "men",
    images: [
      {
        url: "https://picsum.photos/500/500?random=47",
        altText: "slim-fit easy-iron shirt front view",
      },
      {
        url: "https://picsum.photos/500/500?random=2",
        altText: "slim-fit easy-iron shirt front view",
      },
    ],
    rating: 5,
    numReviews: 14,
  },
  {
    name: "polo t-shirt with ribbed collar",
    description:
      "a wardrobe classic, this polo t-shirt features a ribbed collar and cuffs. made from 100% cotton, it offers breathability and comfort throughout the day. tailored in a slim fit with a button placket at the neckline.",
    price: 24.99,
    discountPrice: 19.99,
    countInStock: 50,
    sku: "polo-tsh-006",
    category: "top wear",
    brand: "polo classics",
    sizes: ["s", "m", "l", "xl"],
    colors: ["white", "navy", "red"],
    collections: "casual wear",
    material: "cotton",
    gender: "men",
    images: [
      {
        url: "https://picsum.photos/500/500?random=3",
        altText: "polo t-shirt front view",
      },
      {
        url: "https://picsum.photos/500/500?random=4",
        altText: "polo t-shirt back view",
      },
    ],
    rating: 4.3,
    numReviews: 22,
  },
  {
    name: "oversized graphic t-shirt",
    description:
      "an oversized graphic t-shirt that combines comfort with street style. featuring bold prints across the chest, this relaxed fit tee offers a modern vibe, perfect for pairing with jeans or joggers.",
    price: 19.99,
    discountPrice: 15.99,
    countInStock: 40,
    sku: "ovs-grf-007",
    category: "top wear",
    brand: "street vibes",
    sizes: ["s", "m", "l", "xl"],
    colors: ["black", "gray"],
    collections: "streetwear",
    material: "cotton",
    gender: "men",
    images: [
      {
        url: "https://picsum.photos/500/500?random=5",
        altText: "oversized graphic t-shirt front view",
      },
    ],
    rating: 4.6,
    numReviews: 30,
  },
  {
    name: "regular-fit henley shirt",
    description:
      "a modern take on the classic henley shirt, this regular-fit style features a buttoned placket and ribbed cuffs. made from a soft cotton blend with a touch of elastane for stretch.",
    price: 22.99,
    discountPrice: 18.99,
    countInStock: 35,
    sku: "reg-hen-008",
    category: "top wear",
    brand: "heritage wear",
    sizes: ["s", "m", "l", "xl"],
    colors: ["heather gray", "olive", "black"],
    collections: "casual wear",
    material: "cotton blend",
    gender: "men",
    images: [
      {
        url: "https://picsum.photos/500/500?random=6",
        altText: "regular-fit henley shirt front view",
      },
    ],
    rating: 4.5,
    numReviews: 25,
  },
  {
    name: "long-sleeve thermal tee",
    description:
      "stay warm with this long-sleeve thermal tee, made from soft cotton with a waffle-knit texture. ideal for layering in cooler months, the slim-fit design ensures a snug yet comfortable fit.",
    price: 27.99,
    discountPrice: 22.99,
    countInStock: 20,
    sku: "lst-thr-009",
    category: "top wear",
    brand: "winter basics",
    sizes: ["s", "m", "l", "xl", "xxl"],
    colors: ["charcoal", "dark green", "navy"],
    collections: "winter essentials",
    material: "cotton",
    gender: "men",
    images: [
      {
        url: "https://picsum.photos/500/500?random=7",
        altText: "long-sleeve thermal tee front view",
      },
    ],
    rating: 4.4,
    numReviews: 18,
  },
  {
    name: "v-neck classic t-shirt",
    description:
      "a classic v-neck t-shirt for everyday wear. this regular-fit tee is made from breathable cotton and features a clean, simple design with a flattering v-neckline. lightweight fabric and soft texture make it perfect for casual looks.",
    price: 14.99,
    discountPrice: 11.99,
    countInStock: 60,
    sku: "vneck-cls-010",
    category: "top wear",
    brand: "everyday comfort",
    sizes: ["s", "m", "l", "xl"],
    colors: ["white", "black", "navy"],
    collections: "basics",
    material: "cotton",
    gender: "men",
    images: [
      {
        url: "https://picsum.photos/500/500?random=8",
        altText: "v-neck classic t-shirt front view",
      },
    ],
    rating: 4.7,
    numReviews: 28,
  },
  {
    name: "slim fit joggers",
    description:
      "slim-fit joggers with an elasticated drawstring waist. features ribbed hems and side pockets. ideal for casual outings or workouts.",
    price: 40,
    discountPrice: 35,
    countInStock: 20,
    sku: "bw-001",
    category: "bottom wear",
    brand: "activewear",
    sizes: ["s", "m", "l", "xl"],
    colors: ["black", "gray", "navy"],
    collections: "casual collection",
    material: "cotton blend",
    gender: "men",
    images: [
      {
        url: "https://picsum.photos/500/500?random=9",
        altText: "slim fit joggers front view",
      },
    ],
    rating: 4.5,
    numReviews: 12,
  },
  {
    name: "cargo joggers",
    description:
      "relaxed-fit cargo joggers featuring multiple pockets for functionality. drawstring waist and cuffed hems for a modern look.",
    price: 45,
    discountPrice: 40,
    countInStock: 15,
    sku: "bw-002",
    category: "bottom wear",
    brand: "urbanstyle",
    sizes: ["s", "m", "l", "xl"],
    colors: ["olive", "black"],
    collections: "urban collection",
    material: "cotton",
    gender: "men",
    images: [
      {
        url: "https://picsum.photos/500/500?random=10",
        altText: "cargo joggers front view",
      },
    ],
    rating: 4.7,
    numReviews: 20,
  },
  {
    name: "tapered sweatpants",
    description:
      "tapered sweatpants designed for comfort. elastic waistband with adjustable drawstring, perfect for lounging or athletic activities.",
    price: 35,
    discountPrice: 30,
    countInStock: 25,
    sku: "bw-003",
    category: "bottom wear",
    brand: "chillzone",
    sizes: ["s", "m", "l", "xl"],
    colors: ["gray", "charcoal", "blue"],
    collections: "lounge collection",
    material: "fleece",
    gender: "men",
    images: [
      {
        url: "https://picsum.photos/500/500?random=11",
        altText: "tapered sweatpants front view",
      },
    ],
    rating: 4.3,
    numReviews: 18,
  },
  {
    name: "denim jeans",
    description:
      "classic slim-fit denim jeans with a slight stretch for comfort. features a zip fly and five-pocket styling for a timeless look.",
    price: 60,
    discountPrice: 50,
    countInStock: 30,
    sku: "bw-004",
    category: "bottom wear",
    brand: "denimco",
    sizes: ["s", "m", "l", "xl"],
    colors: ["dark blue", "light blue"],
    collections: "denim collection",
    material: "denim",
    gender: "men",
    images: [
      {
        url: "https://picsum.photos/500/500?random=12",
        altText: "denim jeans front view",
      },
    ],
    rating: 4.6,
    numReviews: 22,
  },
  {
    name: "chino pants",
    description:
      "slim-fit chino pants made from stretch cotton twill. features a button closure and front and back pockets. ideal for both casual and semi-formal wear.",
    price: 55,
    discountPrice: 48,
    countInStock: 40,
    sku: "bw-005",
    category: "bottom wear",
    brand: "casuallook",
    sizes: ["s", "m", "l", "xl"],
    colors: ["beige", "navy", "black"],
    collections: "smart casual collection",
    material: "cotton",
    gender: "men",
    images: [
      {
        url: "https://picsum.photos/500/500?random=13",
        altText: "chino pants front view",
      },
    ],
    rating: 4.8,
    numReviews: 15,
  },
  {
    name: "track pants",
    description:
      "comfortable track pants with an elasticated waistband and tapered leg. features side stripes for a sporty look. ideal for athletic and casual wear.",
    price: 40,
    discountPrice: 35,
    countInStock: 20,
    sku: "bw-006",
    category: "bottom wear",
    brand: "sportx",
    sizes: ["s", "m", "l", "xl"],
    colors: ["black", "red", "blue"],
    collections: "activewear collection",
    material: "polyester",
    gender: "men",
    images: [
      {
        url: "https://picsum.photos/500/500?random=14",
        altText: "track pants front view",
      },
    ],
    rating: 4.2,
    numReviews: 17,
  },
  {
    name: "slim fit trousers",
    description:
      "tailored slim-fit trousers with belt loops and a hook-and-eye closure. suitable for formal occasions or smart-casual wear.",
    price: 65,
    discountPrice: 55,
    countInStock: 15,
    sku: "bw-007",
    category: "bottom wear",
    brand: "executivestyle",
    sizes: ["m", "l", "xl"],
    colors: ["gray", "black"],
    collections: "office wear",
    material: "polyester",
    gender: "men",
    images: [
      {
        url: "https://picsum.photos/500/500?random=15",
        altText: "slim fit trousers front view",
      },
    ],
    rating: 4.7,
    numReviews: 10,
  },
  {
    name: "cargo pants",
    description:
      "loose-fit cargo pants with multiple utility pockets. features adjustable ankle cuffs and a drawstring waist for versatility and comfort.",
    price: 50,
    discountPrice: 45,
    countInStock: 25,
    sku: "bw-008",
    category: "bottom wear",
    brand: "streetwear",
    sizes: ["s", "m", "l", "xl"],
    colors: ["olive", "brown", "black"],
    collections: "street style collection",
    material: "cotton",
    gender: "men",
    images: [
      {
        url: "https://picsum.photos/500/500?random=16",
        altText: "cargo pants front view",
      },
    ],
    rating: 4.5,
    numReviews: 13,
  },
  {
    name: "relaxed fit sweatpants",
    description:
      "relaxed-fit sweatpants made from soft fleece fabric. features an elastic waist and adjustable drawstring for a custom fit.",
    price: 35,
    discountPrice: 30,
    countInStock: 35,
    sku: "bw-009",
    category: "bottom wear",
    brand: "loungewear",
    sizes: ["s", "m", "l", "xl"],
    colors: ["gray", "black", "navy"],
    collections: "lounge collection",
    material: "fleece",
    gender: "men",
    images: [
      {
        url: "https://picsum.photos/500/500?random=17",
        altText: "relaxed fit sweatpants front view",
      },
    ],
    rating: 4.3,
    numReviews: 14,
  },
  {
    name: "formal dress pants",
    description:
      "classic formal dress pants with a slim fit. made from lightweight, wrinkle-resistant fabric for a polished look at the office or formal events.",
    price: 70,
    discountPrice: 60,
    countInStock: 20,
    sku: "bw-010",
    category: "bottom wear",
    brand: "elegantstyle",
    sizes: ["m", "l", "xl"],
    colors: ["black", "navy"],
    collections: "formal collection",
    material: "polyester",
    gender: "men",
    images: [
      {
        url: "https://picsum.photos/500/500?random=18",
        altText: "formal dress pants front view",
      },
    ],
    rating: 4.9,
    numReviews: 8,
  },
  {
    name: "high-waist skinny jeans",
    description:
      "high-waist skinny jeans in stretch denim with a button and zip fly. features a flattering fit that hugs your curves and enhances your silhouette.",
    price: 50,
    discountPrice: 45,
    countInStock: 30,
    sku: "bw-w-001",
    category: "bottom wear",
    brand: "denimstyle",
    sizes: ["xs", "s", "m", "l", "xl"],
    colors: ["dark blue", "black", "light blue"],
    collections: "denim collection",
    material: "denim",
    gender: "women",
    images: [
      {
        url: "https://picsum.photos/500/500?random=19",
        altText: "high-waist skinny jeans",
      },
    ],
    rating: 4.8,
    numReviews: 20,
  },
  {
    name: "wide-leg trousers",
    description:
      "flowy, wide-leg trousers with a high waist and side pockets. perfect for an elegant look that combines comfort and style.",
    price: 60,
    discountPrice: 55,
    countInStock: 25,
    sku: "bw-w-002",
    category: "bottom wear",
    brand: "elegantwear",
    sizes: ["s", "m", "l", "xl"],
    colors: ["beige", "black", "white"],
    collections: "formal collection",
    material: "polyester",
    gender: "women",
    images: [
      {
        url: "https://picsum.photos/500/500?random=20",
        altText: "wide-leg trousers front view",
      },
    ],
    rating: 4.7,
    numReviews: 15,
  },
  {
    name: "stretch leggings",
    description:
      "soft, stretch leggings in a high-rise style. perfect for lounging, working out, or casual wear, with a smooth fit that flatters your body.",
    price: 25,
    discountPrice: 20,
    countInStock: 40,
    sku: "bw-w-003",
    category: "bottom wear",
    brand: "comfyfit",
    sizes: ["s", "m", "l", "xl"],
    colors: ["black", "gray", "navy"],
    collections: "activewear collection",
    material: "cotton blend",
    gender: "women",
    images: [
      {
        url: "https://picsum.photos/500/500?random=21",
        altText: "stretch leggings front view",
      },
    ],
    rating: 4.5,
    numReviews: 30,
  },
  {
    name: "pleated midi skirt",
    description:
      "elegant pleated midi skirt with a high waistband and soft fabric that drapes beautifully. ideal for both formal and casual occasions.",
    price: 55,
    discountPrice: 50,
    countInStock: 20,
    sku: "bw-w-004",
    category: "bottom wear",
    brand: "chicstyle",
    sizes: ["s", "m", "l"],
    colors: ["pink", "navy", "black"],
    collections: "spring collection",
    material: "polyester",
    gender: "women",
    images: [
      {
        url: "https://picsum.photos/500/500?random=22",
        altText: "pleated midi skirt front view",
      },
    ],
    rating: 4.6,
    numReviews: 18,
  },
  {
    name: "flared palazzo pants",
    description:
      "high-waist palazzo pants with a loose, flowing fit. comfortable and stylish, making them perfect for casual outings or beach days.",
    price: 45,
    discountPrice: 40,
    countInStock: 35,
    sku: "bw-w-005",
    category: "bottom wear",
    brand: "breezyvibes",
    sizes: ["s", "m", "l", "xl"],
    colors: ["white", "beige", "light blue"],
    collections: "summer collection",
    material: "linen blend",
    gender: "women",
    images: [
      {
        url: "https://picsum.photos/500/500?random=23",
        altText: "flared palazzo pants front view",
      },
    ],
    rating: 4.4,
    numReviews: 22,
  },
  {
    name: "high-rise joggers",
    description:
      "comfortable high-rise joggers with an elastic waistband and drawstring for a perfect fit. great for lounging or working out.",
    price: 40,
    discountPrice: 35,
    countInStock: 30,
    sku: "bw-w-006",
    category: "bottom wear",
    brand: "activewear",
    sizes: ["xs", "s", "m", "l"],
    colors: ["black", "gray", "pink"],
    collections: "loungewear collection",
    material: "cotton blend",
    gender: "women",
    images: [
      {
        url: "https://picsum.photos/500/500?random=24",
        altText: "high-rise joggers front view",
      },
    ],
    rating: 4.3,
    numReviews: 25,
  },
  {
    name: "paperbag waist shorts",
    description:
      "stylish paperbag waist shorts with a belted waist and wide legs. perfect for summer outings and keeping cool in style.",
    price: 35,
    discountPrice: 30,
    countInStock: 20,
    sku: "bw-w-007",
    category: "bottom wear",
    brand: "sunnystyle",
    sizes: ["s", "m", "l"],
    colors: ["white", "khaki", "blue"],
    collections: "summer collection",
    material: "cotton",
    gender: "women",
    images: [
      {
        url: "https://picsum.photos/500/500?random=25",
        altText: "paperbag waist shorts front view",
      },
    ],
    rating: 4.5,
    numReviews: 19,
  },
  {
    name: "stretch denim shorts",
    description:
      "comfortable stretch denim shorts with a high-waisted fit and raw hem. perfect for pairing with your favorite tops during warmer months.",
    price: 40,
    discountPrice: 35,
    countInStock: 25,
    sku: "bw-w-008",
    category: "bottom wear",
    brand: "denimstyle",
    sizes: ["s", "m", "l", "xl"],
    colors: ["blue", "black", "white"],
    collections: "denim collection",
    material: "denim",
    gender: "women",
    images: [
      {
        url: "https://picsum.photos/500/500?random=26",
        altText: "stretch denim shorts front view",
      },
    ],
    rating: 4.7,
    numReviews: 15,
  },
  {
    name: "culottes",
    description:
      "wide-leg culottes with a flattering high waist and cropped length. the perfect blend of comfort and style for any casual occasion.",
    price: 50,
    discountPrice: 45,
    countInStock: 30,
    sku: "bw-w-009",
    category: "bottom wear",
    brand: "chicstyle",
    sizes: ["s", "m", "l", "xl"],
    colors: ["black", "white", "olive"],
    collections: "casual collection",
    material: "polyester",
    gender: "women",
    images: [
      {
        url: "https://picsum.photos/500/500?random=27",
        altText: "culottes front view",
      },
    ],
    rating: 4.6,
    numReviews: 23,
  },
  {
    name: "classic pleated trousers",
    description:
      "timeless pleated trousers with a tailored fit. a wardrobe essential for workwear or formal occasions.",
    price: 70,
    discountPrice: 65,
    countInStock: 25,
    sku: "bw-w-010",
    category: "bottom wear",
    brand: "elegantwear",
    sizes: ["s", "m", "l", "xl"],
    colors: ["navy", "black", "gray"],
    collections: "formal collection",
    material: "wool blend",
    gender: "women",
    images: [
      {
        url: "https://picsum.photos/500/500?random=28",
        altText: "classic pleated trousers front view",
      },
    ],
    rating: 4.8,
    numReviews: 20,
  },
  {
    name: "knitted cropped top",
    description:
      "a stylish knitted cropped top with a flattering fitted silhouette. perfect for pairing with high-waisted jeans or skirts for a casual look.",
    price: 40,
    discountPrice: 35,
    countInStock: 25,
    sku: "tw-w-001",
    category: "top wear",
    brand: "chicknit",
    sizes: ["s", "m", "l"],
    colors: ["beige", "white"],
    collections: "knits collection",
    material: "cotton blend",
    gender: "women",
    images: [
      {
        url: "https://picsum.photos/500/500?random=29",
        altText: "knitted cropped top",
      },
    ],
    rating: 4.6,
    numReviews: 15,
  },
  {
    name: "boho floral blouse",
    description:
      "flowy boho blouse with floral patterns, featuring a relaxed fit and balloon sleeves. ideal for casual summer days.",
    price: 50,
    discountPrice: 45,
    countInStock: 30,
    sku: "tw-w-002",
    category: "top wear",
    brand: "bohovibes",
    sizes: ["s", "m", "l", "xl"],
    colors: ["white", "pink"],
    collections: "summer collection",
    material: "viscose",
    gender: "women",
    images: [
      {
        url: "https://picsum.photos/500/500?random=30",
        altText: "boho floral blouse",
      },
    ],
    rating: 4.7,
    numReviews: 20,
  },
  {
    name: "casual t-shirt",
    description:
      "a soft, breathable casual t-shirt with a classic fit. features a round neckline and short sleeves, perfect for everyday wear.",
    price: 25,
    discountPrice: 20,
    countInStock: 50,
    sku: "tw-w-003",
    category: "top wear",
    brand: "comfytees",
    sizes: ["s", "m", "l", "xl"],
    colors: ["black", "white", "gray"],
    collections: "essentials",
    material: "cotton",
    gender: "women",
    images: [
      {
        url: "https://picsum.photos/500/500?random=31",
        altText: "casual t-shirt",
      },
    ],
    rating: 4.5,
    numReviews: 25,
  },
  {
    name: "off-shoulder top",
    description:
      "an elegant off-shoulder top with ruffled sleeves and a flattering fit. ideal for adding a touch of femininity to your outfit.",
    price: 45,
    discountprice: 40,
    countinstock: 35,
    sku: "tw-w-004",
    category: "top wear",
    brand: "elegance",
    sizes: ["s", "m", "l"],
    colors: ["red", "white", "blue"],
    collections: "evening collection",
    material: "polyester",
    gender: "women",
    images: [
      {
        url: "https://picsum.photos/500/500?random=32",
        alttext: "off-shoulder top",
      },
    ],
    rating: 4.7,
    numreviews: 18,
  },
  {
    name: "lace-trimmed cami top",
    description:
      "a delicate cami top with lace trim and adjustable straps. the lightweight fabric makes it perfect for layering or wearing alone during warmer weather.",
    price: 35,
    discountprice: 30,
    countinstock: 40,
    sku: "tw-w-005",
    category: "top wear",
    brand: "delicatewear",
    sizes: ["s", "m", "l"],
    colors: ["black", "white"],
    collections: "lingerie-inspired",
    material: "silk blend",
    gender: "women",
    images: [
      {
        url: "https://picsum.photos/500/500?random=33",
        alttext: "lace-trimmed cami top",
      },
    ],
    rating: 4.8,
    numreviews: 22,
  },
  {
    name: "graphic print tee",
    description:
      "a trendy graphic print tee with a relaxed fit. pair it with jeans or skirts for a cool and casual look.",
    price: 30,
    discountprice: 25,
    countinstock: 45,
    sku: "tw-w-006",
    category: "top wear",
    brand: "streetstyle",
    sizes: ["s", "m", "l", "xl"],
    colors: ["white", "black"],
    collections: "urban collection",
    material: "cotton",
    gender: "women",
    images: [
      {
        url: "https://picsum.photos/500/500?random=34",
        alttext: "graphic print tee",
      },
    ],
    rating: 4.6,
    numreviews: 30,
  },
  {
    name: "ribbed long-sleeve top",
    description:
      "a cozy ribbed long-sleeve top that offers comfort and style. perfect for layering during cooler months.",
    price: 55,
    discountprice: 50,
    countinstock: 30,
    sku: "tw-w-007",
    category: "top wear",
    brand: "comfortfit",
    sizes: ["s", "m", "l", "xl"],
    colors: ["gray", "pink", "brown"],
    collections: "fall collection",
    material: "cotton blend",
    gender: "women",
    images: [
      {
        url: "https://picsum.photos/500/500?random=35",
        alttext: "ribbed long-sleeve top",
      },
    ],
    rating: 4.7,
    numreviews: 26,
  },
  {
    name: "ruffle-sleeve blouse",
    description:
      "a lightweight ruffle-sleeve blouse with a flattering fit. perfect for a feminine touch to any outfit.",
    price: 45,
    discountprice: 40,
    countinstock: 20,
    sku: "tw-w-008",
    category: "top wear",
    brand: "femininewear",
    sizes: ["s", "m", "l"],
    colors: ["white", "navy", "lavender"],
    collections: "summer collection",
    material: "viscose",
    gender: "women",
    images: [
      {
        url: "https://picsum.photos/500/500?random=36",
        alttext: "ruffle-sleeve blouse",
      },
    ],
    rating: 4.5,
    numreviews: 19,
  },
  {
    name: "classic button-up shirt",
    description:
      "a versatile button-up shirt that can be dressed up or down. made from soft fabric with a tailored fit, it's perfect for both casual and formal occasions.",
    price: 60,
    discountprice: 55,
    countinstock: 25,
    sku: "tw-w-009",
    category: "top wear",
    brand: "classicstyle",
    sizes: ["s", "m", "l", "xl"],
    colors: ["white", "light blue", "black"],
    collections: "office collection",
    material: "cotton",
    gender: "women",
    images: [
      {
        url: "https://picsum.photos/500/500?random=37",
        alttext: "classic button-up shirt",
      },
    ],
    rating: 4.8,
    numreviews: 25,
  },
  {
    name: "v-neck wrap top",
    description:
      "a chic v-neck wrap top with a tie waist. its elegant style makes it perfect for both casual and semi-formal occasions.",
    price: 50,
    discountprice: 45,
    countinstock: 30,
    sku: "tw-w-010",
    category: "top wear",
    brand: "chicwrap",
    sizes: ["s", "m", "l"],
    colors: ["red", "black", "white"],
    collections: "evening collection",
    material: "polyester",
    gender: "women",
    images: [
      {
        url: "https://picsum.photos/500/500?random=38",
        alttext: "v-neck wrap top",
      },
    ],
    rating: 4.7,
    numreviews: 22,
  },
];
